print("Welcome to Band Name Generator")
print("What's name of the city you grew up in?")
city = input()
print("What's the name of your pet?")
pet = input()
print("Your band name could be "+city+" "+pet)
