# -*- coding: utf-8 -*-
"""Day25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TjA4xta_Sf9w105NTK09XQX5EgfNeA2M
"""

# minimalistic approach
# data = open(".\\100-days-python\\Day25\\weather_data.csv").readlines()
# weather_data = []
# for line in data:
#     weather_data.append(line.strip().split(","))
# print(weather_data)

import csv
import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/svrohith9/100-days-python/main/Day25/weather_data.csv")
temperatures = []
print(data["temp"])

data_dict=data.to_dict()
print(data_dict)

print(f"List of Temps: {data['temp'].to_list()}")
print(f"Avg of Temps: {data['temp'].mean()}")
print(f"Max of Temps: {data['temp'].max()}")
print(f"Min of Temps: {data['temp'].min()}")